### PR TITLE
chore(templating-binding): make class es6

### PR DESCRIPTION
**Pull request by Alxandr**
This allows all of babels transforms to run on the class, as well as discovery by the dts generator.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Good call. I'll get it in soon.

**Comment by EisenbergEffect** [comment]
@Alxandr  I can't accept this as the moment. It breaks the build. This is causing some sort of error with the babel-dts-generator I believe. Can you look into that? I receive errors when running `gulp build`.

**Comment by Alxandr** [comment]
Problem is. I receive errors from building the master branch before making a single change. It's probably true that `babel-dts-generator` doesn't support `[foo]` inside classes, which I can likely fix without too much hassle though.

**Comment by Alxandr** [comment]
@EisenbergEffect The issue _should_ be resolved now (https://github.com/YoloDev/babel-dts-generator/blob/master/spec/class-method.src.js#L8). Would you mind retrying your build (after updating `babel-dts-generator`)?

**Comment by EisenbergEffect** [comment]
@Alxandr First issue down, now we've got another one. When I run the docs generation task (based on TypeDoc) I get the error "A computed property name in an ambient context must directly refer to a built-in symbol." Any idea what that issue is there?

**Comment by EisenbergEffect** [comment]
It seems to work fine on the TypeScript playground...

**Comment by Alxandr** [comment]
Yes. It's probably not a TypeScript problem.

**Comment by EisenbergEffect** [comment]
The error message is originating the the TS compiler I believe though...a quick google search located the message in the TS source. Maybe it's a version thing...

**Comment by EisenbergEffect** [comment]
Nope, the problem is TypeScript. It just only throws the error inside a d.ts file. I'll report the bug to them and see if they can resolve it. Until then, we'll have to wait on this.

**Comment by EisenbergEffect** [comment]
@Alxandr Even thought the class members are declared without brackets, the resulting d.ts files contains brackets in the class definition. It's the brackets, within that particular context, that cause the TS compiler to fail. Would it be possible to update the d.ts generator plugin to not emit the brackets? That should fix the problem. The result should look something like this:

```
  export class SyntaxInterpreter {
    static inject(): any;
    constructor(parser: any, observerLocator: any, eventManager: any);
    interpret(resources: any, element: any, info: any, existingInstruction: any): any;
    handleUnknownCommand(resources: any, element: any, info: any, existingInstruction: any): any;
    determineDefaultBindingMode(element: any, attrName: any): any;
    bind(resources: any, element: any, info: any, existingInstruction: any): any;
    trigger(resources: any, element: any, info: any): any;
    delegate(resources: any, element: any, info: any): any;
    call(resources: any, element: any, info: any, existingInstruction: any): any;
    options(resources: any, element: any, info: any, existingInstruction: any): any;
    'for'(resources: any, element: any, info: any, existingInstruction: any): any;
    'two-way'(resources: any, element: any, info: any, existingInstruction: any): any;
    'one-way'(resources: any, element: any, info: any, existingInstruction: any): any;
    'one-time'(resources: any, element: any, info: any, existingInstruction: any): any;
  }
```

**Comment by Alxandr** [comment]
Sure. Easy even. I just didn't know that was valid. I'll get right on it,
just need to grab some food first.

**Comment by EisenbergEffect** [comment]
No rush. Just let me know.

**Pull request merged**
