### PR TITLE
fix(TemplatingBindingLanguage) escaping, object literals, quoted brackets

### LINKED ISSUE #10: ValueConverter - using object as parameter throws error
I am trying to create a TruncateValueConverter.  This is what I have so far:

<pre>
<code>
export class TruncateValueConverter {
    toView(value, opts) {
        console.log(opts);
        // TODO: Implement value converter
    }    
}
</code>
</pre>

The html is:

<pre>
<code>
${contact.lastName | truncate:{ limit: 10 } } 
</code>
</pre>

I get the following error "Potentially unhandled rejection [2] Error: Parser Error: Missing expected } at the end of the expression [contact.lastName | truncate:{ limit: 10 ]"

### PR DESCRIPTION
**Pull request by jdanyow**
Fixes #10

### CODE REVIEW

**Comment by jdanyow** [comment]
Added tests- let me know if I missed any cases.

**Comment by EisenbergEffect** [comment]
@jdanyow I've also got a PR from Alxander along the same lines. Can you review his implementation as well and give me a summary of the differences. Can you see if either yours or his is faster/slower and in what scenarios? Also, can you investigate the memory pressure effects of both?

You guys have both done really awesome work on this problem. I'd like to make sure all options are carefully considered. I think both implementations are valuable. It's actually pretty nice to have more than option here. Let's see how they compare and also investigate if there's some hybrid solution as well.

**Comment by jdanyow** [comment]
sure- we've been doing quite a bit of that already.  Now that we've got a couple of approaches with tests we just need push this over the finish line.

**Comment by EisenbergEffect** [comment]
Some notes over here: https://github.com/aurelia/templating-binding/issues/18

**Comment by EisenbergEffect** [comment]
@jdanyow Any news on this?

**Comment by jdanyow** [comment]
status update:

Ran my test suite against @Alxandr 's implementation.  Found a few issues, nothing that couldn't be fixed.  Updated him via gitter with the findings.

Created a jsperf to compare both implementations.  The jsperf has two sets of tests for each implementation.  First, the most common scenario, short strings containing plain text or some interpolation expressions.  The second test is a long string interspersed with interpolation expressions.
http://jsperf.com/aurelia-interpolation-allocate-strings/3

PR-17 seems to perform best in most cases.  I think PR-16 could be tweaked to at least match or maybe even surpass PR-17's perf (it's already better in IE) but both are really good alternatives to the current split based implementation that does not meet all the parsing requirements we have.  

I'd say you could merge PR-17 since it's passing the tests and performs well.  If in the future the bugs are worked out of PR-16 and it performs better then those changes could be merged in as a perf enhancement.

**Comment by EisenbergEffect** [comment]
Great. I'll merge 17 today and if we make improvements via 16 we can drop those in down the line. Thanks for heading this up!

**Pull request merged**
